name: FLAKY TEST DEMONSTRAION
on: [push]
jobs:
  _1:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - uses: actions/checkout@v1
      - run: mvn test-compile -am;mvn test -Dtest=org.apache.tapestry5.cdi.test.InjectTest#checkConversationScope
  nondex_error:
    runs-on: ubuntu-latest
    needs: _1
    steps:
      - run: mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.tapestry5.cdi.test.InjectTest#checkConversationScope
