name: FLAKY TEST DEMONSTRAION
on: [push]
jobs:
  _1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - run: git clone https://github.com/amamiya-yuuko-1225/tapestry-cdi_flaky_test_manifestation.git
  _2:
    runs-on: ubuntu-latest
    needs: _1
    steps:
      - run: cd tapestry-cdi_flaky_test_manifestation
  _15:
    runs-on: ubuntu-latest
    needs: _2
    steps:
      - run: mvn test-compile -am
  _3:
    runs-on: ubuntu-latest
    needs: _15
    steps:
      - run: mvn test-compile -am
  _4:
    runs-on: ubuntu-latest
    needs: _3
    steps:
      - run: mvn test -Dtest=org.apache.tapestry5.cdi.test.InjectTest#checkConversationScope
  _5:
    runs-on: ubuntu-latest
    needs: _4
    steps:
      - run: mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.tapestry5.cdi.test.InjectTest#checkConversationScope
