name: FLAKY TEST DEMONSTRAION
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - run: git clone https://github.com/amamiya-yuuko-1225/tapestry-cdi_flaky_test_manifestation.git
      - run: mvn test-compile -am
      - run: mvn test -Dtest=org.apache.tapestry5.cdi.test.InjectTest#checkConversationScope
      - run: mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.tapestry5.cdi.test.InjectTest#checkConversationScope
