name: FLAKY TEST DEMONSTRAION
on: [push]
jobs:
  nondex_test_failed:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.5
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - run: java -version
    - run: git clone https://github.com/worldline/tapestry-cdi.git;cd tapestry-cdi;git checkout 0bd3d11e464b45661c31379e4016c3cc1599b133;mvn test-compile -am;mvn test -Dtest=org.apache.tapestry5.cdi.test.InjectTest#checkConversationScope
  
